version: '3.1'

services:
  python:
    hostname: pyhost
    build:
      context: ./
    restart: always
    ports:
      - 5001:5000
    volumes:
      - ./sources:/app

  db:
    hostname: dbhost
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql

  adminer:
    hostname: adhost
    image: adminer
    restart: always
    ports:
      - 5002:8080
